### ISSUE TITLE
CSRF protection for logging out is missing

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#12]
> ###### Originally posted 2015-10-29 12:52 by *some anonymous* on Bitbucket

![Example](https://prologin.org/user/logout)

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-30 11:16 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 57bdffa.
