### ISSUE TITLE
Nombre de problèmes résolus incorrect

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#13]
> ###### Originally posted 2015-10-31 11:55 by *some anonymous* on Bitbucket

Au questionnaire de sélection 2016, j'ai résolu entièrement 4 problèmes, et j'ai fait plusieurs tentatives ratées sur le dernier. Pourtant, sur la page d'accueil, il est affiché "5/5 problèmes résolus".

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-31 17:44 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

*It's not a bug, it's a feature*. En fait la formulation est incorrecte, ce sont 5 exercices *abordés*. C'est sur la TODO.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-31 19:03 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 28edcf0.
