### ISSUE TITLE
Infos de profil : soucis de typo

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#15]
> ###### Originally posted 2015-11-04 02:40 by [Frigory33](https://bitbucket.org/Frigory33/) on Bitbucket

Dans l'édition des informations de profil et de candidature, on demande une date de naissance au format aaaa-mm-jj, mais quand on la valide, elle devient jj/mm/aaaa. Et quand on revalide, ça reste.
Au final, j'aime autant qu'on indique de mettre du jj/mm/aaaa. C'est plus francophone.

Ensuite, juste en dessous, on demande l'« addresse », avec deux D.

Et dans l'aperçu des infos de profil (statique), il y a une espace juste avant la parenthèse fermante qui suit l'âge. D'ailleurs, ça me paraît bizarre de dire « années » pour un âge, mais bon, vous faites comme vous voulez…

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-16 18:48 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Issues fixed in 983942506140.

> ça me paraît bizarre de dire « années » pour un âge

Django internal. Won't fix.
