### ISSUE TITLE
/user/register/ is not restricted

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#17]
> ###### Originally posted 2015-11-14 18:45 by *some anonymous* on Bitbucket

Users that are already logged in can still access /user/register

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-22 16:23 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 7755a44bba80 among other views.
