### ISSUE TITLE
Date de naissance impossible à compléter

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#19]
> ###### Originally posted 2015-12-26 15:18 by *some anonymous* on Bitbucket

Bonjour,

Le formulaire où l'on renseingne les détails semble ne pas marcher. En effet, en renseignant 23/10/95 comme date de naissance, une erreur m'est retournée. De pls, n'ayant pas d'information quant au format de la date que l'on doit renseigner, je ne peux savoir si c'est un bug, ou juste une erreur lors de la saisie. Ainsi, je ne peux compléter mon inscription au concours.

Bonnes fêtes de fin d'année !

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-01-02 17:01 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Résolu par 90011fd1b8d0.
