### ISSUE TITLE
Localization on center map

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#2]
> ###### Originally posted 2015-10-26 22:14 by [Nurelin](https://bitbucket.org/Nurelin/) on Bitbucket

In French locale, the link to select a center should probably be "Montrer" instead of "Show".
Link : [http://prologin.org/center/](http://prologin.org/center/)

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-26 23:11 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Translation is done. Still have a minor CSS issue.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-27 02:38 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

CSS fixed!
