### ISSUE TITLE
Fautes de frappe/orthographe

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#20]
> ###### Originally posted 2015-12-27 11:42 by [Frigory33](https://bitbucket.org/Frigory33/) on Bitbucket

Sur la page décrivant le QCM : https://prologin.org/about/contest/qualification on voit un gros « EPITCH ».
Dans les pages de classement, il y a une faute dans le message d'information : « notez que seuls les 50 premiers sont visibles, quelque soit le nombre effectif » : « quel que » s'écrit en deux mots ici. Voir https://fr.wiktionary.org/wiki/quel_que_soit.

**Comment by prologin-sandbox** [comment]
> ###### Originally posted 2015-12-27 11:52 by [Frigory33](https://bitbucket.org/Frigory33/) on Bitbucket

Page des demi-finales https://prologin.org/about/contest/semifinals : le E de « mettre en œuvre » n'est pas dans le O qui précède (deux fois dans la page). De plus, les heures sont écrites avec les H collés aux chiffres, alors qu'ils devraient en être dissociés par une espace (insécable bien sûr ; voir https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#Heure) ; et « petit déjeuner » est écrit avec un trait d'union.
Vous remerciant pour la correction de toutes ces erreurs abominables.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-01-02 17:13 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Résolu par b8fb66bcec42.
