### ISSUE TITLE
Ajuster le boutton selectionner un fichier dans la page d'énoncé

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#21]
> ###### Originally posted 2016-01-06 20:12 by *some anonymous* on Bitbucket

Je sais que ce n'est pas très grave comme problème mais comme je suis de nature maniac je vous le dis :P
peut-être ajouter un  "height: auto;" au boutton de sélection de fichier dans la page de soumission :D

Merci pour votre beau travail en tous cas, le site est super bien fait !

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-01-06 20:17 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Merci pour votre suggestion.

La hauteur du champ de fichier est déjà à la bonne valeur : la même que les autres boutons, par exemple ceux en face. Il n'est pas possible de styliser le bouton de sélection lui-même, qui utilise le thème natif du navigateur/OS. C'est une limitation bien connue du champ `<file type="input"/>`. Il faudra donc vous y faire !
