### ISSUE TITLE
Disparition du block "Semi-final"

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#22]
> ###### Originally posted 2016-02-19 09:17 by [QuanticPotato](https://bitbucket.org/QuanticPotato/) on Bitbucket

Depuis 2 jours le block "Semi-final" a disparu de la page d'accueil du site (et donc également les liens vers les centres / infos additionnelles ...)

http://i.imgur.com/6Ukd9re.png

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-02-19 10:36 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

1. Merci de vérifier que le problème existe toujours en désactivant les plugins tels que bloqueurs de publicités.
1. Si le problème persiste sans plugins, peux-tu ouvrir la source de la page d'accueil (Ctrl+U), enregistrer son contenu (certainement Ctrl+S, sinon copier-coller) et l'envoyer en pièce attachée à info -at- prologin.org ? Merci d'avance.

**Comment by prologin-sandbox** [comment]
> ###### Originally posted 2016-02-19 11:00 by [QuanticPotato](https://bitbucket.org/QuanticPotato/) on Bitbucket

Le problème persiste avec tous les addons désactivés. (j'ai envoyé le mail)
Je suis sous Ubuntu 15.04, avec Firefox. 

Je viens de tester sur mon smartphone, et je n'ai pas le bug (le block s'affiche bien)

**Comment by prologin-sandbox** [comment]
> ###### Originally posted 2016-02-19 11:02 by [QuanticPotato](https://bitbucket.org/QuanticPotato/) on Bitbucket

Eratum,

En me connectant avec mon compte prologin (Choups314), j'ai aussi le bug sur mon smartphone en fait (exactement le même, avec un Android lollipop, navigateur par défaut)

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-02-19 11:38 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

C'est noté, mail reçu. Le problème n'est pas général mais lié à ton compte, et certainement d'autres. Nous y travaillons. En attendant, si tu as besoin de la convocation, n'hésite pas à contacter l'équipe par mail.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-02-19 18:35 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Corrigé dans fe9d084. Merci de rouvrir ce ticket si le problème persiste.
