### ISSUE TITLE
Connection impossible

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#24]
> ###### Originally posted 2016-08-10 19:01 by [artemisart](https://bitbucket.org/artemisart/) on Bitbucket

Lors de la connexion à mon compte (pseudo: artemisart) j'obtiens l'erreur 'Ce compte est inactif. '
J'ai essayé de réinitialiser le mot de passe mais je ne reçoit pas non plus de mail (et rien dans les spams).

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-08-10 19:11 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Un e-mail a été envoyé à l'adresse d'inscription. Si tu as changé de mail, merci de nous envoyer un mail.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-08-10 19:48 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Résolu par échange de mails privé.
