### ISSUE TITLE
Impossible de se connecter2

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#25]
> ###### Originally posted 2016-09-18 14:49 by *some anonymous* on Bitbucket

Quand je cherche à me connecter, j'ai le message ce compte est inactif.
Quand je clique sur réinitialiser le mot de passe, je ne reçois rien.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-09-18 14:51 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Bonjour !

Pouvez-vous envoyer un mail à info@prologin.org avec le pseudo et l'email utilisés pour se connecter jusqu'à présent ? Nous verrons ce que l'on peut faire alors.

Merci.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-09-18 16:43 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Résolu avec par échange de mail avec l'intéressé⋅e.
