### ISSUE TITLE
e-mail de réinitialisation de mot de passe non reçu

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#26]
> ###### Originally posted 2016-10-17 11:23 by *some anonymous* on Bitbucket

  Bonjour,
Ayant oublié mon mot de passe, j'ai lancé une demande de réinitialisation de mot de passe il y a 2 jours (juste après le lancement de Prologin 2017).
N'ayant rien reçu, j'ai réessayé 3 ou 4 fois hier, et 2 fois encore ce matin. En vain.
Je me demande donc s'il n'y a pas un problème avec l'envoi automatique d'e-mail.
Pour info :
pseudo : Mohoc
adresse e-mail : `<censurée>` (qui existe bel et bien, je m'y connecte régulièrement. De plus, j'ai bien vérifié dans les spam etc. mais il n'y a nul part trace d'un e-mail de réinitialisation de mot de passe)

Cordialement

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-10-17 11:37 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Bonjour Mohoc,

Ton compte avait été marqué inactif, ce qui est arrivé à plusieurs personnes ayant une adresse email chez free. Nous venons de réactiver ton compte et un nouvel email de réinitialisation t'a été envoyé. N'hésite pas à réouvrir ce bug si ce n'est pas le cas.

Nous sommes désolés pour la gêne occasionnée.

Bonne journée,
