### ISSUE TITLE
Erreur de typo dans l'énoncé du problème 4

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#27]
> ###### Originally posted 2016-10-18 18:09 by *some anonymous* on Bitbucket

Bonjour !
Je viens de remarquer une très légère typo dans le problème 4 "Maximise ton fun !".
Dans les contraintes on a bien sûr "0 <= yi <= **M** - 1" et non "N - 1"
Bonne journée :)
Pierre-Louis 'Pirlout' Sauvage

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-10-18 19:54 by [clement_bc](https://bitbucket.org/clement_bc/) on Bitbucket

Bonjour !
Merci pour la remarque :)
Cependant, les xi et yi sont toutes deux des plateformes, et les plateformes sont des indices entre 0 et N - 1. M désigne uniquement le nombre de pistes.
Bonne journée,
Clément Beauseigneur, vice-président Prologin
