### ISSUE TITLE
Exécution de code impossible en Haskell

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#28]
> ###### Originally posted 2016-10-28 15:28 by [MaloJaffre](https://bitbucket.org/MaloJaffre/) on Bitbucket

Soumettre ce code dans un exercice:
```
#!haskell
main :: IO ()
main = print $ 0
```
donne:
```
/tmp/tmp.6rmkPJcsVL/tmpRAzgbky20r: error while loading shared libraries: libHSbase-4.9.0.0-ghc8.0.1.so: cannot open shared object file: No such file or directory
```
Il semble que la runtime library d'Haskell ne soit pas disponible dans l'environnement d'exécution.

**Comment by prologin-sandbox** [comment]
> ###### Originally posted 2016-11-09 19:07 by [MaloJaffre](https://bitbucket.org/MaloJaffre/) on Bitbucket

Fix:
```haskell
{-# OPTIONS_GHC -optl-static #-}
main :: IO ()
main = print $ 0
```

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-11-09 21:13 by [multun](https://bitbucket.org/multun/) on Bitbucket

Bonsoir,
Ton problème ne semble plus être reproductible depuis mise à jour de ghc.
Rencontres-tu toujours ce problème ?

**Comment by prologin-sandbox** [comment]
> ###### Originally posted 2016-11-10 17:18 by [MaloJaffre](https://bitbucket.org/MaloJaffre/) on Bitbucket

Non, le problème est résolu.
Merci de ton aide.
