### ISSUE TITLE
Problème d'heure

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#3]
> ###### Originally posted 2015-10-26 23:33 by *some anonymous* on Bitbucket

Il n'y aurais pas un décalage dans l'heure lors des soumissions?
Je soumets un code à 23h30 et le site m'indique: "Les résultats de la soumission ne sont plus disponibles parce que le code a été soumis il y a trop longtemps. Vous pouvez toujours essayer de soumettre votre solution en utilisant le boutton « Modifier et re-soumettre »."
L'heure affichée en haut de la page est: "Soumise le 27 octobre 2015 01:30"

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-27 02:41 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

En effet l'heure du serveur était mauvaise ! Nous avons re-synchronisé l'horloge du serveur et ce problème est réglé :)
