### ISSUE TITLE
Non-sticky footer

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#4]
> ###### Originally posted 2015-10-26 23:56 by [reynova](https://bitbucket.org/reynova/ on Bitbucket

Footer should be at the bottom of the page, even on small content pages.

Here is an example of one possible solution:  
 [http://www.lwis.net/profile/CSS/sticky-footer.html](http://www.lwis.net/profile/CSS/sticky-footer.html)

**Comment by prologin-sandbox** [comment]
> ###### Originally posted 2015-10-26 23:58 by [reynova](https://bitbucket.org/reynova/ on Bitbucket

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-22 19:39 by [Zopieux](https://bitbucket.org/Zopieux/ on Bitbucket

There is no clean way of doing this in pure CSS, everything is a hack. The only proper way I know is to use flexboxes but I'm not comfortable using one for the whole page container.
