### ISSUE TITLE
La date n'est pas précisée dans le choix des voeux

### ISSUE THREAD

**Issue by prologin-sandbox** [prologinsandbox/site-issues#6]
> ###### Originally posted 2015-10-27 11:07 by [Gnomino](https://bitbucket.org/Gnomino/) on Bitbucket

Comme dit dans le titre, au moment de choisir des centres d'examen, on a uniquement l'adresse et pas la date, ce qui n'est pas très pratique.
![Centres sans dates.png](https://bitbucket.org/repo/x5L6aA/images/1753873220-Centres%20sans%20dates.png)

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-05 02:49 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

J'ai ajouté les dates vite fait, mais ça ne respecte pas la locale parce que ça utilise strftime(). Et l'affichage n'est pas très joli.
Il faudrait faire ça proprement maintenant.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-05 02:50 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

(Le commit qui ajoute ça est 6d054da5f422)

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-22 19:43 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Fixed in 880918898bfe.
